# CHAPI Azure OpenAI Integration - Docker Compose
version: '3.8'

services:
  chapi-proxy:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://chapibot.pro}
      - PORT=8000
      - HOST=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Telegram bot service
  chapi-telegram:
    build: .
    command: ["python", "telegram_chapi_bot.py"]
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - chapi-proxy
    profiles:
      - telegram